In [1]:
import numpy as np

# 定义一个 3x3 的随机矩阵
a = np.random.rand(3, 3)

# 打印矩阵
print("Before formatting:")
print(a)

# 设置打印格式
def set_np_formatting():
    """ formats numpy print """
    np.set_printoptions(edgeitems=2, infstr='inf',
                        linewidth=40, nanstr='nan', precision=4,
                        suppress=False, threshold=10000, formatter=None)
set_np_formatting()

# 再次打印矩阵
print("After formatting:")
print(a)


Before formatting:
[[0.13666727 0.1178372  0.35754039]
 [0.83258351 0.36042065 0.86701284]
 [0.80602829 0.05762337 0.73478765]]
After formatting:
[[0.1367 0.1178 0.3575]
 [0.8326 0.3604 0.867 ]
 [0.806  0.0576 0.7348]]


In [2]:
import numpy as np

# 创建一个 1 维数组
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 打印数组（默认情况下显示前后各 3 个边缘项）
print("Default edgeitems:")
print(a)

# 设置边缘项数量为 2
np.set_printoptions(edgeitems=2)

# 打印数组（只显示前后各 2 个边缘项）
print("Modified edgeitems:")
print(a)


Default edgeitems:
[1 2 3 4 5 6 7 8 9]
Modified edgeitems:
[1 2 3 4 5 6 7 8 9]


In [7]:
import numpy as np

# 创建一个 2x3 的二维数组
a = np.array([[1, 2, 3], [4, 5, 6]])

# 打印数组（默认情况下显示前后各 3 个边缘项）
print("Default edgeitems:")
print(a)

# 设置边缘项数量为 1
np.set_printoptions(edgeitems=2)

# 打印数组（只显示前后各 1 个边缘项）
print("Modified edgeitems:")
print(a)


Default edgeitems:
[[1 2 3]
 [4 5 6]]
Modified edgeitems:
[[1 2 3]
 [4 5 6]]
